import { registerGeneratorPack, choose } from './generators.js';
import { choiceQuestion, numberQuestion } from './generator-helpers.js';

const exactAngles = [
  { angle:'π/6', sin:'1/2', cos:'√3/2', tan:'√3/3' },
  { angle:'π/4', sin:'√2/2', cos:'√2/2', tan:'1' },
  { angle:'π/3', sin:'√3/2', cos:'1/2', tan:'√3' },
  { angle:'2π/3', sin:'√3/2', cos:'−1/2', tan:'−√3' },
  { angle:'3π/4', sin:'√2/2', cos:'−√2/2', tan:'−1' },
  { angle:'5π/6', sin:'1/2', cos:'−√3/2', tan:'−√3/3' },
  { angle:'7π/6', sin:'−1/2', cos:'−√3/2', tan:'√3/3' },
  { angle:'5π/4', sin:'−√2/2', cos:'−√2/2', tan:'1' },
  { angle:'4π/3', sin:'−√3/2', cos:'−1/2', tan:'√3' },
  { angle:'5π/3', sin:'−√3/2', cos:'1/2', tan:'−√3' },
  { angle:'7π/4', sin:'−√2/2', cos:'√2/2', tan:'−1' },
  { angle:'11π/6', sin:'−1/2', cos:'√3/2', tan:'−√3/3' }
];

const sinSolutions = [
  { value:'1/2', sol:'π/6, 5π/6', wrong:['π/6 only','π/6, 7π/6','5π/6, 11π/6'] },
  { value:'√2/2', sol:'π/4, 3π/4', wrong:['π/4 only','π/4, 5π/4','3π/4, 7π/4'] },
  { value:'−1/2', sol:'7π/6, 11π/6', wrong:['π/6, 5π/6','7π/6 only','5π/6, 7π/6'] },
  { value:'−√2/2', sol:'5π/4, 7π/4', wrong:['π/4, 3π/4','5π/4 only','3π/4, 5π/4'] }
];
const cosSolutions = [
  { value:'1/2', sol:'π/3, 5π/3', wrong:['π/3 only','π/3, 2π/3','2π/3, 4π/3'] },
  { value:'√2/2', sol:'π/4, 7π/4', wrong:['π/4 only','π/4, 3π/4','3π/4, 5π/4'] },
  { value:'−1/2', sol:'2π/3, 4π/3', wrong:['π/3, 5π/3','2π/3 only','2π/3, 5π/3'] },
  { value:'−√2/2', sol:'3π/4, 5π/4', wrong:['π/4, 7π/4','3π/4 only','π/4, 5π/4'] }
];
const tanSolutions = [
  { value:'1', sol:'π/4, 5π/4', wrong:['π/4 only','π/4, 3π/4','3π/4, 7π/4'] },
  { value:'−1', sol:'3π/4, 7π/4', wrong:['π/4, 5π/4','3π/4 only','π/4, 7π/4'] },
  { value:'√3', sol:'π/3, 4π/3', wrong:['π/3 only','π/3, 2π/3','2π/3, 5π/3'] },
  { value:'−√3', sol:'2π/3, 5π/3', wrong:['π/3, 4π/3','2π/3 only','π/3, 5π/3'] }
];

function cq({ rng, conceptId, difficulty, review, prompt, correct, wrong, explanation, steps, hints, feedback={} }) {
  return choiceQuestion({ rng, conceptId, difficulty, review, prompt, correct, distractors:wrong, explanation, steps, hints, feedback });
}

const pack = {
  reciprocalIdentity: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.1 Reciprocal identities',prompt:'Which reciprocal identity is correct?',correct:'sec θ = 1/cos θ',wrong:['sec θ = 1/sin θ','cot θ = 1/cos θ','csc θ = cos θ'],explanation:'Secant is the reciprocal of cosine. The three reciprocal pairs are sin↔csc, cos↔sec, and tan↔cot.',steps:['Pair cosine with secant.','Take the reciprocal: sec θ = 1/cos θ.'],hints:['Say the reciprocal pairs aloud.','Cosine pairs with secant.']}),
  quotientIdentity: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.1 Quotient identities',prompt:'Rewrite tan θ using sine and cosine.',correct:'sin θ / cos θ',wrong:['cos θ / sin θ','1 / cos θ','sin θ · cos θ'],explanation:'The quotient identity is tan θ = sin θ / cos θ. Reversing the quotient gives cotangent.',steps:['Recall tan = opposite/adjacent.','On the unit circle, opposite corresponds to sine and adjacent to cosine.'],hints:['Tangent is the quotient involving sine over cosine.']}),
  rewriteSecTan: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.1 Rewriting with identities',prompt:'Rewrite sec θ · tan θ using only sine and cosine.',correct:'sin θ / cos²θ',wrong:['sin θ / cos θ','cos θ / sin²θ','1 / (sin θ cos θ)'],explanation:'sec θ=1/cos θ and tan θ=sin θ/cos θ, so their product is sin θ/cos²θ.',steps:['Replace sec θ with 1/cos θ.','Replace tan θ with sin θ/cos θ.','Multiply to obtain sin θ/cos²θ.'],hints:['Convert each non-sine/cosine function separately.']}),
  reciprocalEvaluate: ({rng,conceptId,difficulty}) => {
    const item=choose(rng,[{given:'sin θ = 3/5',ask:'csc θ',correct:'5/3',wrong:['3/5','4/5','5/4']},{given:'cos θ = 4/7',ask:'sec θ',correct:'7/4',wrong:['4/7','√33/7','7/√33']},{given:'tan θ = 2/3',ask:'cot θ',correct:'3/2',wrong:['2/3','√13/3','3/√13']}]);
    return cq({rng,conceptId,difficulty,review:'6.1 Reciprocal evaluation',prompt:`If ${item.given}, find ${item.ask}.`,correct:item.correct,wrong:item.wrong,explanation:'Reciprocal identities invert the value of the paired trig function.',steps:[`Identify the reciprocal pair for ${item.ask}.`,'Invert the given ratio.'],hints:['A reciprocal swaps numerator and denominator.']});
  },

  pythagoreanCore: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.2 Pythagorean identities',prompt:'Complete the identity: sin²θ + cos²θ = ?',correct:'1',wrong:['tan²θ','sec²θ','csc²θ'],explanation:'This identity comes directly from x²+y²=1 on the unit circle with x=cosθ and y=sinθ.',steps:['Start with x²+y²=1.','Substitute x=cosθ and y=sinθ.'],hints:['Think of the unit-circle equation.']}),
  pythagoreanTan: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.2 Derived Pythagorean identities',prompt:'Complete the identity: 1 + tan²θ = ?',correct:'sec²θ',wrong:['csc²θ','cot²θ','cos²θ'],explanation:'Divide sin²θ+cos²θ=1 by cos²θ to get tan²θ+1=sec²θ.',steps:['Divide every term in sin²θ+cos²θ=1 by cos²θ.','Simplify each quotient.'],hints:['This identity is built by dividing the core identity by cos²θ.']}),
  pythagoreanCot: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.2 Derived Pythagorean identities',prompt:'Complete the identity: 1 + cot²θ = ?',correct:'csc²θ',wrong:['sec²θ','tan²θ','sin²θ'],explanation:'Divide sin²θ+cos²θ=1 by sin²θ to obtain 1+cot²θ=csc²θ.',steps:['Divide the core identity by sin²θ.','Simplify cos²θ/sin²θ as cot²θ and 1/sin²θ as csc²θ.'],hints:['This version comes from dividing by sin²θ.']}),
  findMissingTrig: ({rng,conceptId,difficulty}) => {
    const item=choose(rng,[{given:'sin θ = 3/5 and θ is in Quadrant I',prompt:'cos θ',correct:'4/5',wrong:['3/5','−4/5','5/4']},{given:'cos θ = −4/5 and θ is in Quadrant II',prompt:'sin θ',correct:'3/5',wrong:['−3/5','4/5','5/3']},{given:'tan θ = 3/4 and θ is in Quadrant III',prompt:'sec θ',correct:'−5/4',wrong:['5/4','−4/5','5/3']}]);
    return cq({rng,conceptId,difficulty,review:'6.2 Finding missing trig values',prompt:`Given ${item.given}, find ${item.prompt}.`,correct:item.correct,wrong:item.wrong,explanation:'Use a Pythagorean identity or reference triangle to get the magnitude, then use the quadrant to determine the sign.',steps:['Find the missing magnitude using a Pythagorean relation.','Apply the quadrant sign.'],hints:['Separate magnitude from sign.','The quadrant tells which trig functions are positive.']});
  },

  simplifyOneMinusSin2: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.3 Simplifying trig expressions',prompt:'Simplify 1 − sin²θ.',correct:'cos²θ',wrong:['sin²θ','sec²θ','1 − cos²θ'],explanation:'Rearrange sin²θ+cos²θ=1 to get 1−sin²θ=cos²θ.',steps:['Write sin²θ+cos²θ=1.','Subtract sin²θ from both sides.'],hints:['Look for a rearranged Pythagorean identity.']}),
  simplifyTanCos: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.3 Quotient simplification',prompt:'Simplify tan θ · cos θ.',correct:'sin θ',wrong:['cos θ','sec θ','sin θ cos θ'],explanation:'tan θ=sinθ/cosθ. Multiplying by cosθ cancels the cosine factor where the expression is defined.',steps:['Replace tanθ with sinθ/cosθ.','Cancel the common cosθ factor.'],hints:['Rewrite tangent first.']}),
  simplifySecMinusCos: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.3 Algebra with identities',prompt:'Simplify (sec θ − cos θ) / tan θ.',correct:'sin θ',wrong:['cos θ','tan θ','csc θ'],explanation:'Rewrite secθ−cosθ as 1/cosθ−cosθ=(1−cos²θ)/cosθ=sin²θ/cosθ. Dividing by tanθ=sinθ/cosθ leaves sinθ.',steps:['Rewrite secθ as 1/cosθ.','Combine: (1−cos²θ)/cosθ.','Use 1−cos²θ=sin²θ.','Divide by sinθ/cosθ and cancel.'],hints:['Convert to sine and cosine.','Use a Pythagorean identity after combining the numerator.']}),
  simplifyCscSin: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.3 Reciprocal simplification',prompt:'Simplify csc θ · sin θ + cos²θ.',correct:'1 + cos²θ',wrong:['sin²θ + cos²θ','cos²θ','2cos²θ'],explanation:'cscθ·sinθ=1 wherever defined, leaving 1+cos²θ.',steps:['Replace cscθ with 1/sinθ.','Cancel sinθ.','Keep the remaining cos²θ term.'],hints:['csc and sin are reciprocals.']}),

  verifyStrategy: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.4 Identity verification strategy',prompt:'Which approach is generally safest when verifying a trig identity?',correct:'Transform one side with valid identities until it matches the other',wrong:['Move all terms to one side and divide by zero if needed','Check one angle numerically and call it proved','Cancel terms across addition'],explanation:'Verification requires algebra that is valid for every value in the common domain. Transforming one side preserves a clear chain of equivalence.',steps:['Choose the more complicated side.','Rewrite with identities/algebra.','Stop once it matches the other side.'],hints:['A numerical check can test, but not prove, an identity.']}),
  verifyFirstStep: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.4 Choosing a first move',prompt:'To verify (1 − cos²θ)/sin θ = sin θ, what is the best first step?',correct:'Replace 1 − cos²θ with sin²θ',wrong:['Cancel 1 with sin θ','Replace sin θ with tan θ','Square both sides immediately'],explanation:'The numerator is exactly a rearranged Pythagorean identity. Replacing it with sin²θ makes cancellation visible.',steps:['Use 1−cos²θ=sin²θ.','Then sin²θ/sinθ=sinθ.'],hints:['Look for a recognizable identity before doing algebra.']}),
  verifyInvalidMove: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.4 Avoiding invalid algebra',prompt:'Which move is NOT valid when verifying an identity?',correct:'Cancel sin θ from the sum sin θ + cos θ',wrong:['Factor a common trig factor','Replace tan θ with sin θ/cos θ','Multiply numerator and denominator by the same nonzero expression'],explanation:'Cancellation works with common factors, not with individual terms separated by addition or subtraction.',steps:['Identify whether the repeated expression is a factor of the entire numerator/denominator.','Do not cancel across addition.'],hints:['Cancellation is really division of common factors.']}),

  solveSinBasic: ({rng,conceptId,difficulty}) => { const i=choose(rng,sinSolutions); return cq({rng,conceptId,difficulty,review:'6.5 Basic sine equations',prompt:`Solve sin x = ${i.value} on 0 ≤ x < 2π.`,correct:i.sol,wrong:i.wrong,explanation:'Find the reference angle, then use the sign of sine to choose every matching quadrant in one full cycle.',steps:['Identify the reference angle.','Choose quadrants where sine has the required sign.','List every solution in [0,2π).'],hints:['Sine is the y-coordinate on the unit circle.']}); },
  solveCosBasic: ({rng,conceptId,difficulty}) => { const i=choose(rng,cosSolutions); return cq({rng,conceptId,difficulty,review:'6.5 Basic cosine equations',prompt:`Solve cos x = ${i.value} on 0 ≤ x < 2π.`,correct:i.sol,wrong:i.wrong,explanation:'Find the reference angle, then choose the quadrants where cosine has the required sign.',steps:['Identify the reference angle.','Use cosine signs by quadrant.','List every solution in the interval.'],hints:['Cosine is the x-coordinate on the unit circle.']}); },
  solveTanBasic: ({rng,conceptId,difficulty}) => { const i=choose(rng,tanSolutions); return cq({rng,conceptId,difficulty,review:'6.5 Basic tangent equations',prompt:`Solve tan x = ${i.value} on 0 ≤ x < 2π.`,correct:i.sol,wrong:i.wrong,explanation:'Tangent repeats every π, so each standard tangent value occurs twice on a full 0-to-2π interval.',steps:['Find one reference-angle solution.','Use tangent’s π-periodicity or the correct sign quadrants.'],hints:['Tangent is positive in Quadrants I and III, negative in II and IV.']}); },

  solveLinearTrig: ({rng,conceptId,difficulty}) => {
    const i=choose(rng,[{eq:'2sin x − 1 = 0',base:'sin x = 1/2',sol:'π/6, 5π/6',wrong:['π/6 only','7π/6, 11π/6','π/3, 2π/3']},{eq:'2cos x + 1 = 0',base:'cos x = −1/2',sol:'2π/3, 4π/3',wrong:['π/3, 5π/3','2π/3 only','π/6, 5π/6']},{eq:'tan x − 1 = 0',base:'tan x = 1',sol:'π/4, 5π/4',wrong:['π/4 only','3π/4, 7π/4','π/2, 3π/2']}]);
    return cq({rng,conceptId,difficulty,review:'6.6 Multi-step trig equations',prompt:`Solve ${i.eq} on 0 ≤ x < 2π.`,correct:i.sol,wrong:i.wrong,explanation:`First use ordinary algebra to isolate the trig expression: ${i.base}. Then solve the resulting basic trig equation on the interval.`,steps:[`Isolate the trig function: ${i.base}.`,'Find all unit-circle solutions in [0,2π).'],hints:['Treat the trig expression like a variable during the algebra step.']});
  },
  solveSquaredTrig: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.6 Squared trig equations',prompt:'Solve 2sin²x − 1 = 0 on 0 ≤ x < 2π.',correct:'π/4, 3π/4, 5π/4, 7π/4',wrong:['π/4, 5π/4','π/2, 3π/2','π/6, 5π/6, 7π/6, 11π/6'],explanation:'Isolate sin²x=1/2, then sinx=±√2/2. Both signs are required, producing four angles.',steps:['2sin²x=1.','sin²x=1/2.','sinx=±√2/2.','List all four unit-circle solutions.'],hints:['Taking the square root creates both a positive and negative case.']}),
  solveFactoredTrig: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.6 Factoring trig equations',prompt:'Solve sin x(2cos x − 1)=0 on 0 ≤ x < 2π.',correct:'0, π/3, π, 5π/3',wrong:['π/3, 5π/3','0, π','π/6, 5π/6, π, 2π'],explanation:'Use the zero-product property: sinx=0 or cosx=1/2. Solve both branches and combine all solutions in the interval.',steps:['Set sinx=0 → x=0,π.','Set 2cosx−1=0 → cosx=1/2.','That branch gives x=π/3,5π/3.','Combine the solution sets.'],hints:['A product is zero when at least one factor is zero.']}),
  solveIdentityEquation: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.6 Equations using identities',prompt:'Solve 1 − cos²x = 3/4 on 0 ≤ x < 2π.',correct:'π/3, 2π/3, 4π/3, 5π/3',wrong:['π/6, 5π/6, 7π/6, 11π/6','π/3, 5π/3','2π/3, 4π/3'],explanation:'Use 1−cos²x=sin²x, so sin²x=3/4 and sinx=±√3/2. That produces four standard angles.',steps:['Replace 1−cos²x with sin²x.','Take square roots: sinx=±√3/2.','List all four solutions.'],hints:['A Pythagorean identity makes this a standard unit-circle equation.']}),

  sumFormulaRecognize: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.7 Sum and difference formulas',prompt:'Which formula equals sin(A+B)?',correct:'sin A cos B + cos A sin B',wrong:['sin A sin B + cos A cos B','sin A cos B − cos A sin B','cos A cos B − sin A sin B'],explanation:'Sine’s sum formula mixes sine-cosine and cosine-sine and keeps the operation sign.',steps:['Recall sin(A±B)=sinAcosB±cosAsinB.'],hints:['Sine mixes the functions and keeps the sign.']}),
  differenceFormulaRecognize: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.7 Sum and difference formulas',prompt:'Which formula equals cos(A−B)?',correct:'cos A cos B + sin A sin B',wrong:['cos A cos B − sin A sin B','sin A cos B − cos A sin B','sin A sin B − cos A cos B'],explanation:'Cosine’s difference formula changes the sign: cos(A−B)=cosAcosB+sinAsinB.',steps:['Recall cos(A±B)=cosAcosB∓sinAsinB.'],hints:['Cosine changes the operation sign.']}),
  exactSumSin: ({rng,conceptId,difficulty}) => {
    const i=choose(rng,[{prompt:'sin 75°',correct:'(√6 + √2)/4',wrong:['(√6 − √2)/4','(√3 + 1)/2','√2/2'],ex:'75°=45°+30°'},{prompt:'sin 15°',correct:'(√6 − √2)/4',wrong:['(√6 + √2)/4','(√3 − 1)/2','1/2'],ex:'15°=45°−30°'}]);
    return cq({rng,conceptId,difficulty,review:'6.7 Exact values with sum/difference',prompt:`Find the exact value of ${i.prompt}.`,correct:i.correct,wrong:i.wrong,explanation:`Use ${i.ex} and the sine sum/difference formula with exact special-angle values.`,steps:[`Rewrite the angle using ${i.ex.split('=')[1]}.`,'Apply the sine formula.','Substitute exact 30° and 45° values and simplify.'],hints:['Break the angle into 30° and 45°.']});
  },
  exactSumCos: ({rng,conceptId,difficulty}) => {
    const i=choose(rng,[{prompt:'cos 75°',correct:'(√6 − √2)/4',wrong:['(√6 + √2)/4','(√3 − 1)/2','√2/2']},{prompt:'cos 15°',correct:'(√6 + √2)/4',wrong:['(√6 − √2)/4','(√3 + 1)/2','1/2']}]);
    return cq({rng,conceptId,difficulty,review:'6.7 Exact values with sum/difference',prompt:`Find the exact value of ${i.prompt}.`,correct:i.correct,wrong:i.wrong,explanation:'Rewrite the angle as 45°±30°, use the cosine sum/difference formula, then substitute exact special-angle values.',steps:['Rewrite the angle as 45°±30°.','Use cos(A±B)=cosAcosB∓sinAsinB.','Substitute and simplify.'],hints:['Cosine changes the sign in its sum/difference formula.']});
  },

  doubleAngleRecognize: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.8 Double-angle formulas',prompt:'Which expression equals sin(2θ)?',correct:'2sin θ cos θ',wrong:['sin²θ − cos²θ','2sin θ','sin²θ + cos²θ'],explanation:'The sine double-angle formula is sin(2θ)=2sinθcosθ.',steps:['Recall the sine sum formula.','Set A=B=θ.'],hints:['Double-angle formulas come from sum formulas with the same angle twice.']}),
  doubleCosRecognize: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.8 Double-angle formulas',prompt:'Which is a valid formula for cos(2θ)?',correct:'cos²θ − sin²θ',wrong:['2sin θ cos θ','cos²θ + sin²θ','2cos θ'],explanation:'cos(2θ)=cos²θ−sin²θ. Equivalent forms are 2cos²θ−1 and 1−2sin²θ.',steps:['Use cos(A+B)=cosAcosB−sinAsinB with A=B=θ.'],hints:['Cosine double-angle is a difference of squares.']}),
  doubleAngleExact: ({rng,conceptId,difficulty}) => {
    const i=choose(rng,[{given:'sin θ=3/5 and cos θ=4/5',ask:'sin(2θ)',correct:'24/25',wrong:['12/25','7/25','1']},{given:'sin θ=5/13 and cos θ=12/13',ask:'cos(2θ)',correct:'119/169',wrong:['120/169','144/169','25/169']}]);
    return cq({rng,conceptId,difficulty,review:'6.8 Evaluating double angles',prompt:`Given ${i.given}, find ${i.ask}.`,correct:i.correct,wrong:i.wrong,explanation:'Substitute the known sine/cosine values into the appropriate double-angle identity and simplify exactly.',steps:['Choose the matching double-angle formula.','Substitute the given values.','Simplify the fraction.'],hints:['For sin(2θ), use 2sinθcosθ. For cos(2θ), choose a cosine double-angle form.']});
  },

  halfAngleRecognize: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.9 Half-angle formulas',prompt:'Which expression equals cos(θ/2)?',correct:'±√((1 + cos θ)/2)',wrong:['±√((1 − cos θ)/2)','(1 + cos θ)/2','2cos θ'],explanation:'The cosine half-angle formula uses 1+cosθ. The sign is chosen from the quadrant containing θ/2.',steps:['Recall cos(θ/2)=±√((1+cosθ)/2).','Determine the sign from θ/2.'],hints:['Cosine half-angle uses the plus sign inside the radical.']}),
  halfAngleSign: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.9 Half-angle signs',prompt:'If π < θ < 2π, what can you say about θ/2?',correct:'π/2 < θ/2 < π, so θ/2 is in Quadrant II',wrong:['0 < θ/2 < π/2, so Quadrant I','π < θ/2 < 2π, so Quadrant III or IV','θ/2 has the same quadrant as θ'],explanation:'Divide every part of the interval π<θ<2π by 2. The half-angle lies between π/2 and π, which is Quadrant II.',steps:['Divide the interval endpoints by 2.','Locate the resulting interval on the unit circle.'],hints:['Half the angle interval before deciding the sign.']}),
  halfAngleExact: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.9 Exact half-angle values',prompt:'Find cos(π/8) exactly.',correct:'√(2 + √2) / 2',wrong:['√(2 − √2) / 2','(1 + √2/2)/2','√2/2'],explanation:'Use θ=π/4 in cos(θ/2)=+√((1+cosθ)/2). Since π/8 is in Quadrant I, choose the positive root.',steps:['Let θ=π/4 so θ/2=π/8.','Substitute cos(π/4)=√2/2.','Simplify the nested radical.'],hints:['π/8 is half of π/4.','The sign is positive in Quadrant I.']}),

  mixedIdentityChoice: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.10 Choosing an identity',prompt:'To simplify (1−cos 2θ)/2, which identity is most direct?',correct:'1 − cos 2θ = 2sin²θ',wrong:['sin 2θ = 2sinθcosθ','1 + tan²θ = sec²θ','cos(A−B)=cosAcosB+sinAsinB'],explanation:'The power-reduction rearrangement 1−cos2θ=2sin²θ immediately turns the expression into sin²θ.',steps:['Recognize the 1−cos2θ pattern.','Replace it with 2sin²θ.','Divide by 2.'],hints:['Look for an identity involving cos(2θ) and sin²θ.']}),
  mixedExactValue: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.10 Mixed formula application',prompt:'If sin θ=3/5 and θ is in Quadrant II, find cos(2θ).',correct:'7/25',wrong:['−7/25','24/25','−24/25'],explanation:'In Quadrant II, cosθ=−4/5. Then cos2θ=cos²θ−sin²θ=16/25−9/25=7/25.',steps:['Use the quadrant to get cosθ=−4/5.','Use cos2θ=cos²θ−sin²θ.','Compute 16/25−9/25=7/25.'],hints:['The sign of cosθ matters before squaring only if you use a formula with cosθ itself; the square becomes positive.']}),
  mixedEquationStrategy: ({rng,conceptId,difficulty}) => cq({rng,conceptId,difficulty,review:'6.10 Strategy',prompt:'You need to solve sin(2x)=√3/2 on 0≤x<2π. What is the best first move?',correct:'Solve for the angle 2x over its corresponding interval, then divide solutions by 2',wrong:['Divide √3/2 by 2','Replace sin(2x) with 2sin x','Take square roots of both sides'],explanation:'Treat 2x as the angle input. Because x spans [0,2π), 2x spans [0,4π). Solve the sine equation there, then divide each angle by 2.',steps:['Let u=2x.','Solve sinu=√3/2 on 0≤u<4π.','Convert back with x=u/2.'],hints:['The doubled input changes the interval and number of solutions.']})
};

registerGeneratorPack('u6', pack);
export default pack;
